### PR TITLE
Slow down looping tooltips in diagram

### PR DESCRIPTION
**Pull request by lynnandtonic**

### CODE REVIEW

**Comment by lynnandtonic** [comment]
This can merge whenever!

**Comment by crcastle** [comment]
Merged and re-deployed.  @justjenu @vrana2011 what do you think of the architecture diagram caption display speed now? https://twitter-display.herokuapp.com/

**Comment by justjenu** [comment]
I like this speed but would like it to start sooner? Right now you don't know it is even there as it takes a while to load. cc: @crcastle @lynnandtonic ( also @vrana2011 agrees)

**Comment by lynnandtonic** [comment]
@justjenu I have it set up so the messages don't start until the grey dots reach the final UI at the end of the flow. They should still start sooner?

**Comment by justjenu** [comment]
@lynnandtonic yes - as no one will see that there are mouseovers here - think it should start almost right away.

**Comment by lynnandtonic** [comment]
@justjenu Ok sounds good.

**Pull request merged**
